version: "3.9"
name: yarp-reverse-proxy

services:

  yarp-api:
    image: hubviwe/yarp.reverse.proxy.api:1.0.0
    container_name: yarp-api
    restart: on-failure
    build:
        context: src/
        dockerfile: API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password!
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
    ports:
      - 7229:443
      - 5246:80
    depends_on:
      - token-api

  token-api:
    image: hubviwe/jwtauthentication.token.api:1.0.11
    hostname: token-api
    container_name: token-api
    restart: on-failure
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    depends_on:
      - mongo
      - jaeger

  mongo:
    image: mongo
    hostname: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  jaeger:
    image: jaegertracing/all-in-one
    hostname: jaeger
    container_name: jaeger
    environment:
      COLLECTOR_OTLP_ENABLED: true
    ports:
      - 16686:16686 # jaeger ui
      - 4317:4317 # accept OpenTelemetry Protocol (OTLP) over gRPC
      - 4318:4318 # accept OpenTelemetry Protocol (OTLP) over HTTP