version: "3.9"
name: yarp-reverse-proxy

services:

  token-api:
    image: hubviwe/jwtauthentication.token.api:1.0.11
    container_name: token-api
    restart: on-failure
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password!
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/jwt-authentication.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
    ports:
      - 5161:80
      - 7161:443
    depends_on:
      - mongo
      - jaeger

  mongo:
    image: mongo
    hostname: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  jaeger:
    image: jaegertracing/all-in-one
    hostname: jaeger
    container_name: jaeger
    environment:
      COLLECTOR_OTLP_ENABLED: true
    ports:
      - 16686:16686 # jaeger ui
      - 4317:4317 # accept OpenTelemetry Protocol (OTLP) over gRPC
      - 4318:4318 # accept OpenTelemetry Protocol (OTLP) over HTTP